[project]
name = "ComfyUI_D00MYsNodes"
description = "Nodes: D00MYs_Images_to_PNG, D00MYs_Show_String."
version = "0.0.1"
license = {}

[project.urls]
Repository = hhttps://github.com/doomy23/ComfyUI-D00MYsNodes/"

[tool.comfy]
PublisherId = "doomy23"
DisplayName = "ComfyUI_D00MYsNodes"
Icon = ""
